#!/usr/bin/env ruby

git_bundles = %w{
    https://github.com/LaTeX-Box-Team/LaTeX-Box.git
}

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.rm_rf(bundles_dir)
FileUtils.mkdir(bundles_dir)
FileUtils.cd(bundles_dir)

git_bundles.each do |url|
  puts url
  `git clone -q #{url}`
  puts "done"
end

Dir["*/.git"].each {|f| FileUtils.rm_rf(f) }

